---
- hosts: all
  tasks:
    - name: Ensure applications directory exists
      file:
        path: ~/.local/share/applications
        state: directory

    - name: Copy .desktop file for CodeOpen
      copy:
        src: files/codeopen.desktop
        dest: ~/.local/share/applications/codeopen.desktop

    - name: Ensure MIME packages directory exists
      file:
        path: ~/.local/share/mime/packages
        state: directory

    - name: Copy MIME type XML file
      copy:
        src: files/codeopen.xml
        dest: ~/.local/share/mime/packages/codeopen.xml

    - name: Update MIME database
      shell: update-mime-database ~/.local/share/mime

    - name: Update desktop database
      shell: update-desktop-database ~/.local/share/applications

    - name: Register .codeopen file type with CodeOpen application
      shell: xdg-mime default codeopen.desktop application/x-codeopen
