---
- name: Ensure applications directory exists
  file:
    path: ~/.local/share/applications
    state: directory

- name: Copy .desktop file for FolderCode
  copy:
    src: files/foldercode.desktop
    dest: ~/.local/share/applications/foldercode.desktop

- name: Ensure MIME packages directory exists
  file:
    path: ~/.local/share/mime/packages
    state: directory

- name: Copy MIME type XML file
  copy:
    src: files/foldercode.xml
    dest: ~/.local/share/mime/packages/foldercode.xml

- name: Update MIME database
  shell: update-mime-database ~/.local/share/mime

- name: Update desktop database
  shell: update-desktop-database ~/.local/share/applications

- name: Register .foldercode file type with FolderCode application
  shell: xdg-mime default foldercode.desktop application/x-foldercode
